version: '3.2'
services:
  postgres:
    restart: always
    image: postgres:11.1
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=testresult
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    volumes:
    - ./testresult.sql:/docker-entrypoint-initdb.d/init.sql

  webapi:
    restart: always
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres